//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

[Serializable]
public class EnemyData : IData
{
    public int ID => key;

    public int key;
    public string enemy_name;
    public int enemy_type;
    public int enemy_hp;
    public int enemy_move;
    public int enemy_damage;
    public float enemy_cooldown;
    public bool enemy_patrol;
    public int enemy_patroldata;
    public float enemy_detectrange;
    public float enemy_attackrange;
}

[Serializable]
public class EnemyDataTable
{
    public List<EnemyData> enemydata;
}
