//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

[Serializable]
public class ItemData : IData
{
    public int ID => key;

    public int key;
    public string item_name;
    public string item_desc;
    public int item_hprecovery;
}

[Serializable]
public class ItemDataTable
{
    public List<ItemData> itemdata;
}
