//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

[Serializable]
public class PlayerData
{
    public int player_hp;
    public int player_dam;
    public float player_mov;
    public float player_jump;
    public float smash_cooldown;
}
